-- update_comments.sql
-- Preview editable de comments. Modifica los textos y ejecuta este script para aplicar cambios.
SET NAMES utf8mb4;

-- 1) Comments de tablas
ALTER TABLE `linaarti` COMMENT = 'Artículos';
ALTER TABLE `linaartr` COMMENT = 'Rubros de Artículos';
ALTER TABLE `linabanc` COMMENT = 'Movimientos de Bancos';
ALTER TABLE `linacaja` COMMENT = 'Movimientos de Caja';
ALTER TABLE `linaclie` COMMENT = 'Clientes';
ALTER TABLE `linacode` COMMENT = 'Cobranzas - Detalle';
ALTER TABLE `linacodm` COMMENT = 'Códigos de Movimiento';
ALTER TABLE `linacohe` COMMENT = 'Cobranzas - Cabeceras';
ALTER TABLE `linactcl` COMMENT = 'Cuentas Corrientes de Clientes';
ALTER TABLE `linactpr` COMMENT = 'Cuentas Corrientes de Proveedores';
ALTER TABLE `linaempr` COMMENT = 'Empresas';
ALTER TABLE `linaerro` COMMENT = 'Errores de Ejecución';
ALTER TABLE `linafcde` COMMENT = 'Facturación Compras - Detalle';
ALTER TABLE `linafche` COMMENT = 'Facturación Compras - Cabeceras';
ALTER TABLE `linafvde` COMMENT = 'Facturación Ventas - Detalle';
ALTER TABLE `linafvhe` COMMENT = 'Facturación Ventas - Cabeceraa';
ALTER TABLE `linamixt` COMMENT = 'Mixto de Configuración';
ALTER TABLE `linapade` COMMENT = 'Pagos - Detalle';
ALTER TABLE `linapahe` COMMENT = 'Pagos - Cabecera';
ALTER TABLE `linaprog` COMMENT = 'Programas del Sistema';
ALTER TABLE `linaprov` COMMENT = 'Proveedores';
ALTER TABLE `linasafe` COMMENT = 'Permisos de Usuarios';
ALTER TABLE `linatabl` COMMENT = 'Tablas del Sistema';
ALTER TABLE `linauser` COMMENT = 'Usuarios del Sistema';

-- 2) Comments de columnas (preserva definicion de cada columna)
ALTER TABLE `linaarti` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linaarti` MODIFY COLUMN `articodi` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo Articulo';
ALTER TABLE `linaarti` MODIFY COLUMN `artrcodi` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Rubro del Articulo';
ALTER TABLE `linaarti` MODIFY COLUMN `artidesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripción del Articulo';
ALTER TABLE `linaarti` MODIFY COLUMN `artiexan` int NOT NULL DEFAULT '0' COMMENT 'Existencia Anterior Cantidad';
ALTER TABLE `linaarti` MODIFY COLUMN `artiexfe` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Existencia Anterior Fecha';
ALTER TABLE `linaarti` MODIFY COLUMN `artipmpe` int NOT NULL DEFAULT '0' COMMENT 'Punto Minimo de Pedido';
ALTER TABLE `linaarti` MODIFY COLUMN `artiucco` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Costo Ultima Compra';
ALTER TABLE `linaarti` MODIFY COLUMN `artiucfe` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Ultima Compra';
ALTER TABLE `linaarti` MODIFY COLUMN `artiucca` int NOT NULL DEFAULT '0' COMMENT 'Cantidad Ultima Compra';
ALTER TABLE `linaarti` MODIFY COLUMN `artiprec` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Precio de Venta';
ALTER TABLE `linaarti` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaarti` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaarti` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaarti` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaarti` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaarti` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaarti` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linaartr` MODIFY COLUMN `artrcodi` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Rubro';
ALTER TABLE `linaartr` MODIFY COLUMN `artrdesc` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion del Rubro';
ALTER TABLE `linaartr` MODIFY COLUMN `artrsalp` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Salto de Pagina (S/N)';
ALTER TABLE `linaartr` MODIFY COLUMN `artrsala` int NOT NULL DEFAULT '0' COMMENT 'Renglones Antes';
ALTER TABLE `linaartr` MODIFY COLUMN `artrsald` int NOT NULL DEFAULT '0' COMMENT 'Renglones Despues';
ALTER TABLE `linaartr` MODIFY COLUMN `artrsubr` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Caracter de Subrayado';
ALTER TABLE `linaartr` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaartr` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `bancid` int NOT NULL auto_increment COMMENT 'PK autoincremental linabanc';
ALTER TABLE `linabanc` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Código de Empresa';
ALTER TABLE `linabanc` MODIFY COLUMN `cliecodi` int NOT NULL DEFAULT '0' COMMENT 'Código de Cliente';
ALTER TABLE `linabanc` MODIFY COLUMN `provcodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Proveedor';
ALTER TABLE `linabanc` MODIFY COLUMN `bancfech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Movimiento';
ALTER TABLE `linabanc` MODIFY COLUMN `bancnumc` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante Origen';
ALTER TABLE `linabanc` MODIFY COLUMN `bancconc` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Concepto';
ALTER TABLE `linabanc` MODIFY COLUMN `bancdebe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe Debito';
ALTER TABLE `linabanc` MODIFY COLUMN `banchabe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe Credito';
ALTER TABLE `linabanc` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linabanc` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `cajaid` int NOT NULL auto_increment COMMENT 'PK autoincremental linacaja';
ALTER TABLE `linacaja` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Código de Empresa';
ALTER TABLE `linacaja` MODIFY COLUMN `cliecodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Cliente';
ALTER TABLE `linacaja` MODIFY COLUMN `provcodi` int NOT NULL COMMENT 'Codigo de Proveedor';
ALTER TABLE `linacaja` MODIFY COLUMN `cajafech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Movmiento';
ALTER TABLE `linacaja` MODIFY COLUMN `cajanumc` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante Origen';
ALTER TABLE `linacaja` MODIFY COLUMN `cajaconc` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Concepto';
ALTER TABLE `linacaja` MODIFY COLUMN `cajadebe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe Debito';
ALTER TABLE `linacaja` MODIFY COLUMN `cajahabe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe Credito';
ALTER TABLE `linacaja` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacaja` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linaclie` MODIFY COLUMN `cliecodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Cliente';
ALTER TABLE `linaclie` MODIFY COLUMN `cliename` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Nombre del Cliente';
ALTER TABLE `linaclie` MODIFY COLUMN `cliesala` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Saldo Anterior';
ALTER TABLE `linaclie` MODIFY COLUMN `cliefesa` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Saldo Anterior';
ALTER TABLE `linaclie` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaclie` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linacode` MODIFY COLUMN `cohenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linacode` MODIFY COLUMN `codereng` int NOT NULL DEFAULT '0' COMMENT 'Numero de Renglon';
ALTER TABLE `linacode` MODIFY COLUMN `codedesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion del Concepto';
ALTER TABLE `linacode` MODIFY COLUMN `codeunit` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Precio Unitario';
ALTER TABLE `linacode` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacode` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `codmclpr` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Aplica a <C>liente ó a <P>roveedor';
ALTER TABLE `linacodm` MODIFY COLUMN `codmdecr` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Es <D>ébito ó <C>rédito';
ALTER TABLE `linacodm` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linacodm` MODIFY COLUMN `codmdesc` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion';
ALTER TABLE `linacodm` MODIFY COLUMN `codmultn` int NOT NULL DEFAULT '0' COMMENT 'Ultimo Numero Usado';
ALTER TABLE `linacodm` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacodm` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linacohe` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linacohe` MODIFY COLUMN `cohenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linacohe` MODIFY COLUMN `cohefech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Comprobante';
ALTER TABLE `linacohe` MODIFY COLUMN `cliecodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Cliente';
ALTER TABLE `linacohe` MODIFY COLUMN `cohetota` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Total Comprobante';
ALTER TABLE `linacohe` MODIFY COLUMN `coheefec` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Cobrado en Efectivo';
ALTER TABLE `linacohe` MODIFY COLUMN `cohebanc` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Cobrado en Transf. o Deposito';
ALTER TABLE `linacohe` MODIFY COLUMN `coheobse` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Observaciones';
ALTER TABLE `linacohe` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linacohe` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `ctclid` int NOT NULL auto_increment COMMENT 'PK autoincremental linactcl';
ALTER TABLE `linactcl` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linactcl` MODIFY COLUMN `cliecodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Cliente';
ALTER TABLE `linactcl` MODIFY COLUMN `ctclfech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Movimiento';
ALTER TABLE `linactcl` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linactcl` MODIFY COLUMN `ctclnumc` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linactcl` MODIFY COLUMN `ctcldebe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe al Debe';
ALTER TABLE `linactcl` MODIFY COLUMN `ctclhabe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe al Haber';
ALTER TABLE `linactcl` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactcl` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `ctprid` int NOT NULL auto_increment COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linactpr` MODIFY COLUMN `provcodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Proveedor';
ALTER TABLE `linactpr` MODIFY COLUMN `ctprfech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Movimiento';
ALTER TABLE `linactpr` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linactpr` MODIFY COLUMN `ctprnumc` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linactpr` MODIFY COLUMN `ctprdebe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe al Debe';
ALTER TABLE `linactpr` MODIFY COLUMN `ctprhabe` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Importe al Haber';
ALTER TABLE `linactpr` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linactpr` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Empresa';
ALTER TABLE `linaempr` MODIFY COLUMN `emprname` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Razon Social';
ALTER TABLE `linaempr` MODIFY COLUMN `emprdire` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Direccion';
ALTER TABLE `linaempr` MODIFY COLUMN `emprcodp` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo Postal';
ALTER TABLE `linaempr` MODIFY COLUMN `emprloca` varchar(34) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Localidad';
ALTER TABLE `linaempr` MODIFY COLUMN `emprtele` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Telefono';
ALTER TABLE `linaempr` MODIFY COLUMN `emprciva` int NOT NULL DEFAULT '0' COMMENT 'Condicion frente a IVA';
ALTER TABLE `linaempr` MODIFY COLUMN `emprcgan` int NOT NULL DEFAULT '0' COMMENT 'Condicion frente a Ganancias';
ALTER TABLE `linaempr` MODIFY COLUMN `emprcuit` decimal(11,0) NOT NULL DEFAULT '0' COMMENT 'CUIT';
ALTER TABLE `linaempr` MODIFY COLUMN `emprunid` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Unidad de Trabajo';
ALTER TABLE `linaempr` MODIFY COLUMN `emprnume` int NOT NULL DEFAULT '0' COMMENT 'Control (Name+Dire)';
ALTER TABLE `linaempr` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaempr` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linaerro` MODIFY COLUMN `erroid` int NOT NULL auto_increment COMMENT 'PK autoincremental linaerro';
ALTER TABLE `linaerro` MODIFY COLUMN `errowstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Id. Error';
ALTER TABLE `linaerro` MODIFY COLUMN `errouser` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Usuario';
ALTER TABLE `linaerro` MODIFY COLUMN `errodate` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha';
ALTER TABLE `linaerro` MODIFY COLUMN `errotime` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Hora';
ALTER TABLE `linaerro` MODIFY COLUMN `erroempr` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Empresa';
ALTER TABLE `linaerro` MODIFY COLUMN `erronume` int NOT NULL DEFAULT '0' COMMENT 'Número de Error';
ALTER TABLE `linaerro` MODIFY COLUMN `erromssg` varchar(78) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Mensaje' COMMENT '';
ALTER TABLE `linaerro` MODIFY COLUMN `errosour` varchar(78) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Código fuente' COMMENT '';
ALTER TABLE `linaerro` MODIFY COLUMN `erroline` int NOT NULL DEFAULT '0' COMMENT 'Línea';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg0` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 0';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg1` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 1';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg2` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 2';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg3` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 3';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg4` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 4';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg5` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 5';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg6` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 6';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg7` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 7';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg8` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Nivel 8';
ALTER TABLE `linaerro` MODIFY COLUMN `erroprg9` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linafcde` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linafcde` MODIFY COLUMN `fchenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linafcde` MODIFY COLUMN `fcdereng` int NOT NULL DEFAULT '0' COMMENT 'Renglon del Comprobante';
ALTER TABLE `linafcde` MODIFY COLUMN `fcdefech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Movimiento para CARDEX';
ALTER TABLE `linafcde` MODIFY COLUMN `articodi` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Articulo';
ALTER TABLE `linafcde` MODIFY COLUMN `fcdedesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion del Item';
ALTER TABLE `linafcde` MODIFY COLUMN `fcdecant` int NOT NULL DEFAULT '0' COMMENT 'Cantidad';
ALTER TABLE `linafcde` MODIFY COLUMN `fcdeunit` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Precio Unitario';
ALTER TABLE `linafcde` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafcde` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linafche` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linafche` MODIFY COLUMN `fchenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linafche` MODIFY COLUMN `fchefech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Comprobante';
ALTER TABLE `linafche` MODIFY COLUMN `provcodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Proveedor';
ALTER TABLE `linafche` MODIFY COLUMN `fchetota` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Total Comprobante';
ALTER TABLE `linafche` MODIFY COLUMN `fcheobse` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Observaciones';
ALTER TABLE `linafche` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafche` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linafvde` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linafvde` MODIFY COLUMN `fvhenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linafvde` MODIFY COLUMN `fvdereng` int NOT NULL DEFAULT '0' COMMENT 'Numero de Renglon';
ALTER TABLE `linafvde` MODIFY COLUMN `fvhefech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Movimiento para CARDEX';
ALTER TABLE `linafvde` MODIFY COLUMN `articodi` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Articulo';
ALTER TABLE `linafvde` MODIFY COLUMN `fvdedesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion del Item';
ALTER TABLE `linafvde` MODIFY COLUMN `fvdecant` int NOT NULL DEFAULT '0' COMMENT 'Cantidad';
ALTER TABLE `linafvde` MODIFY COLUMN `fvdeunit` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Unitario';
ALTER TABLE `linafvde` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvde` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linafvhe` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linafvhe` MODIFY COLUMN `fvhenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linafvhe` MODIFY COLUMN `fvhefech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Comprobante';
ALTER TABLE `linafvhe` MODIFY COLUMN `cliecodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Cliente';
ALTER TABLE `linafvhe` MODIFY COLUMN `fvhetota` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Total Comprobante';
ALTER TABLE `linafvhe` MODIFY COLUMN `fvheobse` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Observaciones';
ALTER TABLE `linafvhe` MODIFY COLUMN `fvhereci` int NOT NULL DEFAULT '0' COMMENT 'Numero de Recibo Simultaneo a Factura';
ALTER TABLE `linafvhe` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linafvhe` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linamixt` MODIFY COLUMN `mixtclav` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linamixt` MODIFY COLUMN `mixtdato` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linamixt` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linapade` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linapade` MODIFY COLUMN `pahenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linapade` MODIFY COLUMN `padereng` int NOT NULL DEFAULT '0' COMMENT 'Numero de Renglon';
ALTER TABLE `linapade` MODIFY COLUMN `padedesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion del Concepto';
ALTER TABLE `linapade` MODIFY COLUMN `padeunit` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Unitario';
ALTER TABLE `linapade` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapade` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linapahe` MODIFY COLUMN `codmcodi` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Movimiento';
ALTER TABLE `linapahe` MODIFY COLUMN `pahenume` int NOT NULL DEFAULT '0' COMMENT 'Numero de Comprobante';
ALTER TABLE `linapahe` MODIFY COLUMN `pahefech` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Comprobante';
ALTER TABLE `linapahe` MODIFY COLUMN `provcodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Proveedor';
ALTER TABLE `linapahe` MODIFY COLUMN `pahetota` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Total Comprobante';
ALTER TABLE `linapahe` MODIFY COLUMN `paheefec` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Pagado en Efectivo';
ALTER TABLE `linapahe` MODIFY COLUMN `pahebanc` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Pagado con Transferencia ó Depósito';
ALTER TABLE `linapahe` MODIFY COLUMN `paheobse` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Observaciones';
ALTER TABLE `linapahe` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linapahe` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `progcodi` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Programa';
ALTER TABLE `linaprog` MODIFY COLUMN `progcall` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Tipo de Miembro';
ALTER TABLE `linaprog` MODIFY COLUMN `progdesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion';
ALTER TABLE `linaprog` MODIFY COLUMN `progowne` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Programa Particular de Este Owner';
ALTER TABLE `linaprog` MODIFY COLUMN `progexsu` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Si Puede Ejecutarse Desde SUCU#01';
ALTER TABLE `linaprog` MODIFY COLUMN `progexre` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Si Puede Ejecutarse Remotamente';
ALTER TABLE `linaprog` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprog` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linaprov` MODIFY COLUMN `provcodi` int NOT NULL DEFAULT '0' COMMENT 'Codigo de Proveedor';
ALTER TABLE `linaprov` MODIFY COLUMN `provname` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Nombre';
ALTER TABLE `linaprov` MODIFY COLUMN `provsala` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT 'Saldo Anterior';
ALTER TABLE `linaprov` MODIFY COLUMN `provfesa` date NOT NULL DEFAULT '1900-01-01' COMMENT 'Fecha Saldo Anterior';
ALTER TABLE `linaprov` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linaprov` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linasafe` MODIFY COLUMN `usercodi` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `progcodi` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Código de Programa en linaprog';
ALTER TABLE `linasafe` MODIFY COLUMN `safealta` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Autorizacion para Altas';
ALTER TABLE `linasafe` MODIFY COLUMN `safebaja` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Autorizacion para Bajas';
ALTER TABLE `linasafe` MODIFY COLUMN `safemodi` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Autorizacion para Modificaciones';
ALTER TABLE `linasafe` MODIFY COLUMN `safecons` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Autorizacion para Consultas';
ALTER TABLE `linasafe` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linasafe` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
ALTER TABLE `linatabl` MODIFY COLUMN `tablcodi` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Codigo de Tabla (Alias)';
ALTER TABLE `linatabl` MODIFY COLUMN `tabltipo` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Tipo de Tabla [S]istema o [E]Mpresa';
ALTER TABLE `linatabl` MODIFY COLUMN `tabldesc` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Descripcion';
ALTER TABLE `linauser` MODIFY COLUMN `emprcodi` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código de Empresa';
ALTER TABLE `linauser` MODIFY COLUMN `usercodi` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `username` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Nombre';
ALTER TABLE `linauser` MODIFY COLUMN `userpass` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Password SHA2-256';
ALTER TABLE `linauser` MODIFY COLUMN `userremo` int NOT NULL DEFAULT '0' COMMENT 'Si Es Usuario Remoto';
ALTER TABLE `linauser` MODIFY COLUMN `user` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `date` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `time` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `oper` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `prog` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `wstn` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '';
ALTER TABLE `linauser` MODIFY COLUMN `nume` int NOT NULL DEFAULT '0' COMMENT '';
